import { BoschEntity } from '../types/BoschFeaturesTypes';
import { EBoschFeature } from './BoschFeatures';

export enum EBoschEntity {
  active_program,
  alarm_clock,
  alarm_clock_value,
  base_program,
  brilliance_dry,
  childlock,
  connected,
  current_cavity_temperature,
  door_state,
  duration,
  elapsed_program_time,
  eco_dry,
  extra_dry,
  fast_preheat,
  half_load,
  hygiene_plus,
  intensive_zone,
  interior_illumination_active,
  local_control_active,
  operation_state,
  power_state,
  program_name,
  program_progress,
  programs,
  remaining_program_time,
  remaining_program_time_is_estimated,
  remote_control_active,
  remote_control_start_allowed,
  sabbath_mode,
  selected_program,
  set_point_temperature,
  set_point_temperature_value,
  silence_on_demand,
  start_in_relative,
  start_in_relative_value,
  start_pause,
  steam_assist_level,
  stop,
  vario_speed_plus,
  weight,
  zeolite_dry,
}

export const boschEntitiesMap: Map<EBoschEntity, BoschEntity> = new Map([
  [EBoschEntity.active_program, { type: 'sensor', suffix: 'active_program' }],
  [EBoschEntity.alarm_clock, { type: 'sensor', suffix: 'bsh_common_setting_alarmclock' }],
  [EBoschEntity.alarm_clock_value, { type: 'number', suffix: 'bsh_common_setting_alarmclock' }],
  [EBoschEntity.base_program, { type: 'sensor', suffix: 'bsh_common_option_baseprogram' }],
  [EBoschEntity.brilliance_dry, { type: 'switch', suffix: 'dishcare_dishwasher_option_brilliancedry' }],
  [EBoschEntity.childlock, { type: 'binary_sensor', suffix: 'bsh_common_setting_childlock' }],
  [EBoschEntity.connected, { type: 'binary_sensor', suffix: 'connected' }],
  [EBoschEntity.current_cavity_temperature, { type: 'sensor', suffix: 'cooking_oven_status_currentcavitytemperature' }],
  [EBoschEntity.door_state, { type: 'binary_sensor', suffix: 'bsh_common_status_doorstate' }],
  [EBoschEntity.duration, { type: 'sensor', suffix: 'bsh_common_option_duration' }],
  [EBoschEntity.elapsed_program_time, { type: 'sensor', suffix: 'bsh_common_option_elapsedprogramtime' }],
  [EBoschEntity.eco_dry, { type: 'switch', suffix: 'dishcare_dishwasher_option_ecodry' }],
  [EBoschEntity.extra_dry, { type: 'switch', suffix: 'dishcare_dishwasher_option_extradry' }],
  [EBoschEntity.fast_preheat, { type: 'switch', suffix: 'cooking_oven_option_fastpreheat' }],
  [EBoschEntity.half_load, { type: 'switch', suffix: 'dishcare_dishwasher_option_halfload' }],
  [EBoschEntity.hygiene_plus, { type: 'switch', suffix: 'dishcare_dishwasher_option_hygieneplus' }],
  [EBoschEntity.intensive_zone, { type: 'switch', suffix: 'dishcare_dishwasher_option_intensivzone' }],
  [EBoschEntity.interior_illumination_active, { type: 'binary_sensor', suffix: 'bsh_common_status_interiorilluminationactive' }],
  [EBoschEntity.local_control_active, { type: 'binary_sensor', suffix: 'bsh_common_status_localcontrolactive' }],
  [EBoschEntity.operation_state, { type: 'sensor', suffix: 'bsh_common_status_operationstate' }],
  [EBoschEntity.power_state, { type: 'switch', suffix: 'bsh_common_setting_powerstate' }],
  [EBoschEntity.program_name, { type: 'sensor', suffix: 'bsh_common_option_programname' }],
  [EBoschEntity.program_progress, { type: 'sensor', suffix: 'bsh_common_option_programprogress' }],
  [EBoschEntity.programs, { type: 'select', suffix: 'programs' }],
  [EBoschEntity.remaining_program_time, { type: 'sensor', suffix: 'bsh_common_option_remainingprogramtime' }],
  [EBoschEntity.remaining_program_time_is_estimated, { type: 'binary_sensor', suffix: 'bsh_common_option_remainingprogramtimeisestimated' }],
  [EBoschEntity.remote_control_active, { type: 'binary_sensor', suffix: 'bsh_common_status_remotecontrolactive' }],
  [EBoschEntity.remote_control_start_allowed, { type: 'binary_sensor', suffix: 'bsh_common_status_remotecontrolstartallowed' }],
  [EBoschEntity.sabbath_mode, { type: 'switch', suffix: 'cooking_oven_setting_sabbathmode' }],
  [EBoschEntity.selected_program, { type: 'sensor', suffix: 'selected_program' }],
  [EBoschEntity.set_point_temperature, { type: 'sensor', suffix: 'cooking_oven_option_setpointtemperature' }],
  [EBoschEntity.set_point_temperature_value, { type: 'number', suffix: 'cooking_oven_option_setpointtemperature' }],
  [EBoschEntity.silence_on_demand, { type: 'switch', suffix: 'dishcare_dishwasher_option_silenceondemand' }],
  [EBoschEntity.start_in_relative, { type: 'select', suffix: 'bsh_common_option_startinrelative' }],
  [EBoschEntity.start_in_relative_value, { type: 'number', suffix: 'bsh_common_option_startinrelative' }],
  [EBoschEntity.start_pause, { type: 'button', suffix: 'start_pause' }],
  [EBoschEntity.steam_assist_level, { type: 'sensor', suffix: 'cooking_oven_option_steamassistlevel' }],
  [EBoschEntity.stop, { type: 'button', suffix: 'stop' }],
  [EBoschEntity.vario_speed_plus, { type: 'switch', suffix: 'dishcare_dishwasher_option_variospeedplus' }],
  [EBoschEntity.weight, { type: 'sensor', suffix: 'cooking_oven_option_weight' }],
  [EBoschEntity.zeolite_dry, { type: 'switch', suffix: 'dishcare_dishwasher_option_zeolitedry' }],
]);

export const boschFeatureEntitiesMap: Map<EBoschFeature, EBoschEntity[]> = new Map([
  [
    EBoschFeature.dishwasher_programs,
    [
      EBoschEntity.active_program,
      EBoschEntity.base_program,
      EBoschEntity.connected,
      EBoschEntity.door_state,
      EBoschEntity.operation_state,
      EBoschEntity.power_state,
      EBoschEntity.program_name,
      EBoschEntity.programs,
      EBoschEntity.remaining_program_time_is_estimated,
      EBoschEntity.remote_control_active,
      EBoschEntity.remote_control_start_allowed,
      EBoschEntity.selected_program,
    ],
  ],
  [
    EBoschFeature.dishwasher_options,
    [
      EBoschEntity.connected,
      EBoschEntity.door_state,
      EBoschEntity.extra_dry,
      EBoschEntity.hygiene_plus,
      EBoschEntity.intensive_zone,
      EBoschEntity.operation_state,
      EBoschEntity.power_state,
      EBoschEntity.remote_control_active,
      EBoschEntity.remote_control_start_allowed,
      EBoschEntity.silence_on_demand,
      EBoschEntity.vario_speed_plus,
    ],
  ],
  [
    EBoschFeature.dishwasher_time,
    [
      EBoschEntity.connected,
      EBoschEntity.door_state,
      EBoschEntity.operation_state,
      EBoschEntity.power_state,
      EBoschEntity.program_progress,
      EBoschEntity.remaining_program_time,
      EBoschEntity.remote_control_active,
      EBoschEntity.remote_control_start_allowed,
      EBoschEntity.start_pause,
      EBoschEntity.stop,
    ],
  ],
  [
    EBoschFeature.oven_controls,
    [
      EBoschEntity.active_program,
      EBoschEntity.alarm_clock,
      EBoschEntity.alarm_clock_value,
      EBoschEntity.childlock,
      EBoschEntity.connected,
      EBoschEntity.current_cavity_temperature,
      EBoschEntity.door_state,
      EBoschEntity.duration,
      EBoschEntity.elapsed_program_time,
      EBoschEntity.fast_preheat,
      EBoschEntity.interior_illumination_active,
      EBoschEntity.local_control_active,
      EBoschEntity.operation_state,
      EBoschEntity.power_state,
      EBoschEntity.program_progress,
      EBoschEntity.programs,
      EBoschEntity.remaining_program_time,
      EBoschEntity.remaining_program_time_is_estimated,
      EBoschEntity.remote_control_active,
      EBoschEntity.remote_control_start_allowed,
      EBoschEntity.sabbath_mode,
      EBoschEntity.selected_program,
      EBoschEntity.set_point_temperature,
      EBoschEntity.set_point_temperature_value,
      EBoschEntity.start_in_relative,
      EBoschEntity.start_in_relative_value,
      EBoschEntity.start_pause,
      EBoschEntity.steam_assist_level,
      EBoschEntity.stop,
      EBoschEntity.weight,
    ],
  ],
]);
