import { EBoschFeature } from "./BoschFeatures";

export enum EBoschEntity {
    active_program,
    base_program,
    brilliance_dry,
    connected,
    door_state,
    eco_dry,
    extra_dry,
    half_load,
    hygiene_plus,
    intensive_zone,
    operation_state,
    power_state,
    program_name,
    program_progress,
    programs,
    remaining_program_time,
    remaining_program_time_is_estimated,
    remote_control_active,
    remote_control_start_allowed,
    selected_program,
    silence_on_demand,
    start_in_relative,
    start_pause,
    stop,
    vario_speed_plus,
    zeolite_dry
}

export const boschEntitiesMap: Map<EBoschEntity, BoschEntity> = new Map([
    [EBoschEntity.active_program, { type: "sensor", suffix: "active_program" }],
    [EBoschEntity.base_program, { type: "sensor", suffix: "bsh_common_option_baseprogram" }],
    [EBoschEntity.brilliance_dry, { type: "switch", suffix: "dishcare_dishwasher_option_brilliancedry" }],
    [EBoschEntity.connected, { type: "binary_sensor", suffix: "connected" }],
    [EBoschEntity.door_state, { type: "binary_sensor", suffix: "bsh_common_status_doorstate" }],
    [EBoschEntity.eco_dry, { type: "switch", suffix: "dishcare_dishwasher_option_ecodry" }],
    [EBoschEntity.extra_dry, { type: "switch", suffix: "dishcare_dishwasher_option_extradry" }],
    [EBoschEntity.half_load, { type: "switch", suffix: "dishcare_dishwasher_option_halfload" }],
    [EBoschEntity.hygiene_plus, { type: "switch", suffix: "dishcare_dishwasher_option_hygieneplus" }],
    [EBoschEntity.intensive_zone, { type: "switch", suffix: "dishcare_dishwasher_option_intensivzone" }],
    [EBoschEntity.operation_state, { type: "sensor", suffix: "bsh_common_status_operationstate" }],
    [EBoschEntity.power_state, { type: "switch", suffix: "bsh_common_setting_powerstate" }],
    [EBoschEntity.program_name, { type: "sensor", suffix: "bsh_common_option_programname" }],
    [EBoschEntity.program_progress, { type: "sensor", suffix: "bsh_common_option_programprogress" }],
    [EBoschEntity.programs, { type: "select", suffix: "programs" }],
    [EBoschEntity.remaining_program_time, { type: "sensor", suffix: "bsh_common_option_remainingprogramtime" }],
    [EBoschEntity.remaining_program_time_is_estimated, { type: "binary_sensor", suffix: "bsh_common_option_remainingprogramtimeisestimated" }],
    [EBoschEntity.remote_control_active, { type: "binary_sensor", suffix: "bsh_common_status_remotecontrolactive" }],
    [EBoschEntity.remote_control_start_allowed, { type: "binary_sensor", suffix: "bsh_common_status_remotecontrolstartallowed" }],
    [EBoschEntity.selected_program, { type: "sensor", suffix: "selected_program" }],
    [EBoschEntity.silence_on_demand, { type: "switch", suffix: "dishcare_dishwasher_option_silenceondemand" }],
    [EBoschEntity.start_in_relative, { type: "select", suffix: "bsh_common_option_startinrelative" }],
    [EBoschEntity.start_pause, { type: "button", suffix: "start_pause" }],
    [EBoschEntity.stop, { type: "button", suffix: "stop" }],
    [EBoschEntity.vario_speed_plus, { type: "switch", suffix: "dishcare_dishwasher_option_variospeedplus" }],
    [EBoschEntity.zeolite_dry, { type: "switch", suffix: "dishcare_dishwasher_option_zeolitedry" }],
]);

export const boschFeatureEntitiesMap: Map<EBoschFeature, EBoschEntity[]> = new Map([
    [EBoschFeature.dishwasher_programs, [
        EBoschEntity.active_program,
        EBoschEntity.base_program,
        EBoschEntity.connected,
        EBoschEntity.door_state,
        EBoschEntity.operation_state,
        EBoschEntity.program_name,
        EBoschEntity.programs,
        EBoschEntity.remaining_program_time_is_estimated,
        EBoschEntity.remote_control_active,
        EBoschEntity.remote_control_start_allowed,
        EBoschEntity.selected_program,
    ]],
    [EBoschFeature.dishwasher_options, [
        EBoschEntity.connected,
        EBoschEntity.door_state,
        EBoschEntity.extra_dry,
        EBoschEntity.hygiene_plus,
        EBoschEntity.intensive_zone,
        EBoschEntity.operation_state,
        EBoschEntity.power_state,
        EBoschEntity.remote_control_active,
        EBoschEntity.remote_control_start_allowed,
        EBoschEntity.silence_on_demand,
        EBoschEntity.vario_speed_plus,
    ]],
    [EBoschFeature.dishwasher_time, [
        EBoschEntity.connected,
        EBoschEntity.door_state,
        EBoschEntity.operation_state,
        EBoschEntity.power_state,
        EBoschEntity.program_progress,
        EBoschEntity.remaining_program_time,
        EBoschEntity.remaining_program_time_is_estimated,
        EBoschEntity.remote_control_active,
        EBoschEntity.remote_control_start_allowed,
        EBoschEntity.start_in_relative,
        EBoschEntity.start_pause,
        EBoschEntity.stop,
    ]],
]);
